### ISSUE TITLE
Sentinel should be configurable per-target

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/rupture#173]
Sentinels are currently [hard coded](https://github.com/dionyziz/rupture/blob/develop/backend/breach/strategy.py#L95). This should be configurable per-target. Add the respective field in the model, create and run a database migration, use it in the strategy module, and modify the population scripts to fill it in as required. You can make the default value be '^' if you like.

**Comment by esarafianou** [comment]
fixed in #189
