### ISSUE TITLE
Rendering of Com / Enc

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/rupture#259]
The rendering of "Com" and "Enc" look ugly – can we do something about them? It looks as if they are each comprised of three variables C - o - m through their italicised rendering.

**Comment by dimkarakostas** [comment]
Not sure how, perhaps rename "Enc" -> "E" and "Com" -> "C"?

**Comment by dionyziz** [comment]
That will be confusing; we use \mathcal{E} to mean Enc o Com and c to mean ciphertext, so E and C are not good choices. Can we try rendering them without italics?

**Comment by dimkarakostas** [comment]
I used normal text in equations. Check latest version of #257
